# Generated by Django 2.2.2 on 2020-03-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='is_super_user_perm',
            field=models.BooleanField(default=False, verbose_name='Only super user'),
        ),
    ]
